### PR TITLE
Frontend: Change - Render "Edit with elementor" button in the client side.

### LINKED ISSUE #11728: "Edit with Elementor" isn't clickable after the first page load
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
When visiting a post, the first load will successfully show the Edit with Elementor button. If you refresh the page (or load it in another tab), the button stops appearing.

If you edit the post with Elementor and save, then it will appear one more time, but stops appearing after that.

This problem is closely related to issue #10745, but the two issues are a bit different. The old issue was fixed with pull request #10889, but this problem still persists even in the latest stable release.

I did some simple debugging and found that this line in `\includes\frontend.php` was failing:

`if ( is_singular() && isset($this->admin_bar_edit_documents[$queried_object_id]))`

The problem there seems to be that the

`1626 => Elementor\Core\DocumentTypes\Post::__set_state(array( 'main_id' => 1626, 'post' => WP_Post...`

value is missing from the admin_bar_edit_documents array after the first page load.

Any idea what's happening there?

## Steps to reproduce
1. Create a post with Elementor and publish it
2. View the page and note that the "Edit with Elementor" button appears at the top and is clickable.
3. Refresh the page and note that the button has disappeared (or at least isn't clickable).

## Isolating the problem

- [x] This bug happens with only the Elementor plugin active.
- [x] The bug is unrelated to Elementor Pro (it happens regardless of whether or not Elementor Pro is installed/activated).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug 100% of the time using the steps above.

## Environment

<details>
<summary>System Info</summary>

```
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: MariaDB Server v10.3.23
	PHP Version: 7.0.33
	PHP Max Input Vars: 2000
	PHP Max Post Size: 3000M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.4.2
	Site URL: (hidden)
	Home URL: (hidden)
	WP Multisite: No
	Max Upload Size: 3 GB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: America/New_York
	Debug Mode: Inactive

== Theme ==
	Name: Astra
	Version: 2.4.5
	Author: Brainstorm Force
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 2.9.11
		Author: Elementor.com


== Elements Usage ==
	
	wp-post : 2
		html : 1
		text-editor : 1
	wp-page : 1
		heading : 1
		text-editor : 2


== Log ==
	
Log: showing 17 of 172019-08-29 23:06:04 [info] elementor::elementor_updater Started 
2019-08-29 23:06:04 [info] Elementor/Upgrades - _v_2_6_0_fa4_migration_flag Start  
2019-08-29 23:06:04 [info] Elementor/Upgrades - _v_2_6_0_fa4_migration_flag Finished 
2019-08-29 23:06:04 [info] Elementor/Upgrades - _v_2_6_6_fa4_migration_button Start  
2019-08-29 23:06:04 [info] Elementor/Upgrades - _v_2_6_6_fa4_migration_button Finished 
2019-08-29 23:06:04 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.16',
  'to' => '2.6.8',
)]
2019-08-29 23:06:04 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '2.5.16',
  'to' => '2.6.8',
)]
2020-05-28 08:23:26 [info] elementor::elementor_updater Started 
2020-05-28 08:23:26 [info] Elementor/Upgrades - _v_2_7_1_remove_old_usage_data Start  
2020-05-28 08:23:26 [info] Elementor/Upgrades - _v_2_7_1_remove_old_usage_data Finished 
2020-05-28 08:23:26 [info] Elementor/Upgrades - _v_2_7_1_recalc_usage_data Start  
2020-05-28 08:23:26 [info] Elementor/Upgrades - _v_2_7_1_recalc_usage_data Finished 
2020-05-28 08:23:26 [info] Elementor/Upgrades - _v_2_8_3_recalc_usage_data Start  
2020-05-28 08:23:26 [info] Elementor/Upgrades - _v_2_8_3_recalc_usage_data Finished 
2020-05-28 08:23:26 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.6.8',
  'to' => '2.9.9',
)]
2020-05-28 08:23:26 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '2.6.8',
  'to' => '2.9.9',
)]
2020-06-10 07:22:29 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.9',
  'to' => '2.9.11',
)]			
```
</details>

### PR DESCRIPTION
**Pull request by Nevoss**
fix #11728, #12175.

### CODE REVIEW

File: includes/frontend.php [hunk 1]
```diff
@@ -1017,48 +1014,6 @@ public function add_document_to_admin_bar( $css_file ) {
...
-	 * allows the user to edit with Elementor.
-	 *
-	 * Fired by `admin_bar_menu` action.
-	 *
-	 * @since 1.3.4
-	 * @access public
-	 *
-	 * @param \WP_Admin_Bar $wp_admin_bar WP_Admin_Bar instance, passed by reference.
-	 */
-	public function add_menu_in_admin_bar( \WP_Admin_Bar $wp_admin_bar ) {
```
Comment (matipojo) [inline includes/frontend.php:1033]: Keep this method. but add to the JS config instead of `$wp_admin_bar`.

**Review by matipojo — CHANGES_REQUESTED** [review]

File: modules/admin-bar/module.php [hunk 2]
```diff
@@ -0,0 +1,124 @@
...
+		 * @since 3.0.0
+		 */
+		return apply_filters( 'elementor/frontend/admin_bar/settings', $settings );
+	}
+
+	/**
+	 * Module constructor.
+	 */
+	public function __construct() {
+		// Detect Elementor documents via their css that printed before the Admin Bar.
```
Comment (matipojo) [inline modules/admin-bar/module.php:120]:
```suggestion
```

File: tests/phpunit/elementor/modules/admin-bar/test-module.php [hunk 3]
```diff
@@ -0,0 +1,43 @@
...
+
+		/** \WP_Query $wp_query */
+		global $wp_query;
+
+		$active_post = $this->factory()->create_and_get_default_post();
+		$post = $this->factory()->create_and_get_default_post();
+
+		$wp_query->queried_object = $active_post;
+		$wp_query->queried_object_id = $active_post->ID;
+		$wp_query->is_singular = true;
```
Comment (matipojo) [inline tests/phpunit/elementor/modules/admin-bar/test-module.php:24]:
```suggestion
		query_posts( [ 'p' => $active_post->ID ] );
```

File: tests/phpunit/elementor/modules/admin-bar/test-module.php [hunk 4]
```diff
@@ -0,0 +1,43 @@
...
+
+		$adminBarModule = new Module();
+
+		do_action( 'elementor/frontend/get_builder_content', $active_document = Plugin::$instance->documents->get( $active_post->ID ) );
```
Comment (matipojo) [inline tests/phpunit/elementor/modules/admin-bar/test-module.php:28]:
```suggestion
		Plugin::$instance->frontend->get_builder_content( $active_post->ID );
```

File: tests/phpunit/elementor/modules/admin-bar/test-module.php [hunk 5]
```diff
@@ -0,0 +1,43 @@
...
+		do_action( 'elementor/frontend/get_builder_content', $document = Plugin::$instance->documents->get( $post->ID ) );
```
Comment (matipojo) [inline tests/phpunit/elementor/modules/admin-bar/test-module.php:29]: Like ^^^

**Review by matipojo — CHANGES_REQUESTED** [review]

File: includes/frontend.php [hunk 6]
```diff
@@ -967,6 +955,8 @@ public function get_builder_content( $post_id, $with_css = false ) {
 			}
 
 			$css_file->enqueue();
+
+			do_action( 'elementor/frontend/get_builder_content', $document );
```
Comment (matipojo) [inline includes/frontend.php:959]: Move the end of method

**Review by matipojo — CHANGES_REQUESTED** [review]

File: tests/phpunit/elementor/modules/admin-bar/test-module.php [hunk 7]
```diff
@@ -0,0 +1,106 @@
...
+
+		$frontend->get_builder_content( $not_supported_document->get_id() );
+
+		$config = $this->module->get_admin_bar_config();
+
+		$editButtonConfig = $config['elementor_app_site_editor'];
+
+		$this->assertCount( 1, $editButtonConfig['children'] );
+		$this->assertEquals( "elementor_app_site_editor", $editButtonConfig['children'][0]['id'] );
+		$this->assertFalse( isset( $editButtonConfig['href'] ) );
```
Comment (matipojo) [inline tests/phpunit/elementor/modules/admin-bar/test-module.php:80]: `assertNotContains`?
anyway, don't trust the `elementor_app_site_editor` item as an indicator (here and next text) . it may be removed.

File: tests/phpunit/elementor/modules/admin-bar/test-module.php [hunk 8]
```diff
@@ -0,0 +1,106 @@
...
+				'_elementor_template_type' => 'not-supported'
+				// The prop 'show_on_admin_bar' of NotSupport document type is false.
+			],
+		] );
+
+		$frontend = Plugin::$instance->frontend;
+
+		$frontend->start_excerpt_flag( $excerpt_document->get_id() );
+		$frontend->get_builder_content( $excerpt_document->get_id() );
+		$frontend->end_excerpt_flag( $excerpt_document->get_id() );
```
Comment (matipojo) [inline tests/phpunit/elementor/modules/admin-bar/test-module.php:70]: `// Emulate an excerpt on fronend.`

**Review by matipojo — CHANGES_REQUESTED** [review]

File: modules/admin-bar/module.php [hunk 9]
```diff
@@ -0,0 +1,128 @@
...
+		}
+
+		$this->documents[ $document->get_main_id() ] = $document;
+	}
+
+	/**
+	 * Scripts for module.
+	 */
+	public function enqueue_scripts() {
+		wp_enqueue_script(
```
Comment (matipojo) [inline modules/admin-bar/module.php:54]: Check if has `$this->documents`;

**Review by matipojo — CHANGES_REQUESTED** [review]

File: tests/phpunit/elementor/modules/admin-bar/test-module.php [hunk 10]
```diff
@@ -0,0 +1,106 @@
...
+
+		$frontend->get_builder_content( $not_supported_document->get_id() );
+
+		$config = $this->module->get_admin_bar_config();
+
+		$editButtonConfig = $config['elementor_edit_page'];
+
+		$this->assertCount( 1, $editButtonConfig['children'] );
+		$this->assertEquals( "elementor_app_site_editor", $editButtonConfig['children'][0]['id'] );
```
Comment (matipojo) [inline tests/phpunit/elementor/modules/admin-bar/test-module.php:79]: Remove the assert of `elementor_app_site_editor`, try `!in_array`

**Review by matipojo — CHANGES_REQUESTED** [review]

File: tests/phpunit/elementor/modules/admin-bar/test-module.php [hunk 11]
```diff
@@ -0,0 +1,105 @@
...
+		$this->assertCount( 1, $editButtonConfig['children'] );
+		$this->assertEquals( "elementor_edit_doc_{$document->get_id()}", $editButtonConfig['children'][ $document->get_id() ]['id'] );
+	}
+
+	public function test_it_should_not_add_document_that_is_not_valid() {
+		$excerpt_document = $this->create_document();
+		$not_supported_document = $this->create_document( [
+			'meta_input' => [
+				'_elementor_template_type' => 'not-supported'
+				// The prop 'show_on_admin_bar' of NotSupport document type is false.
```
Comment (matipojo) [inline tests/phpunit/elementor/modules/admin-bar/test-module.php:66]:
```suggestion
				// The prop 'show_on_admin_bar' of NotSupport document type is false.
				'_elementor_template_type' => 'not-supported'
```

File: tests/phpunit/elementor/modules/admin-bar/test-module.php [hunk 12]
```diff
@@ -0,0 +1,105 @@
...
+		// Emulate an excerpt on frontend.
+		$frontend->start_excerpt_flag( $excerpt_document->get_id() );
+		$frontend->get_builder_content( $excerpt_document->get_id() );
+		$frontend->end_excerpt_flag( $excerpt_document->get_id() );
+
+		$frontend->get_builder_content( $not_supported_document->get_id() );
+
+		$config = $this->module->get_admin_bar_config();
+
+		$this->assertEmpty( $config );
```
Comment (matipojo) [inline tests/phpunit/elementor/modules/admin-bar/test-module.php:81]: If it fails you can't know immediately which document fails. please assert separately for each document (in same test) with a test description.

**Review by matipojo — CHANGES_REQUESTED** [review]

**Review by matipojo — DISMISSED** [review]

File: modules/admin-bar/module.php [hunk 13]
```diff
@@ -0,0 +1,132 @@
...
+			$this->get_admin_bar_config()
+		);
+	}
+
+	/**
+	 * Creates the config for 'Edit with elementor' menu item.
+	 *
+	 * @return array
+	 */
+	protected function get_edit_button_config() {
```
Comment (kobizz) [inline modules/admin-bar/module.php:78]: Can this method be private?

File: modules/admin-bar/module.php [hunk 14]
```diff
@@ -0,0 +1,132 @@
...
+class Module extends BaseModule {
+	/**
+	 * @var Document[]
+	 */
+	private $documents = [];
+
+	/**
+	 * @return bool
+	 */
+	public static function is_active() {
```
Comment (kobizz) [inline modules/admin-bar/module.php:21]: Where is this method used?

File: modules/admin-bar/module.php [hunk 15]
```diff
@@ -0,0 +1,132 @@
...
+			}, $this->documents ),
+		];
+	}
+
+	/**
+	 * Creates admin bar menu items config.
+	 *
+	 * @return array
+	 */
+	public function get_admin_bar_config() {
```
Comment (kobizz) [inline modules/admin-bar/module.php:108]: Use the built-in `get_init_settings()` method.

Call the settings by `get_settings()` method

File: modules/admin-bar/module.php [hunk 16]
```diff
@@ -0,0 +1,132 @@
...
+			[ 'elementor-common' ],
+			ELEMENTOR_VERSION,
+			true
+		);
+
+		wp_localize_script(
+			'elementor-admin-bar',
+			'elementor_admin_bar',
+			$this->get_admin_bar_config()
+		);
```
Comment (kobizz) [inline modules/admin-bar/module.php:70]: If the admin-bar module uses its own config, it's better to extend it from `Core\Base\App`

**Review by kobizz — CHANGES_REQUESTED** [review]

File: modules/admin-bar/module.php (hunk 14 above)
Comment (Nevoss) [reply modules/admin-bar/module.php:21]: The Module Manager calls this method before it registers the module.

File: modules/admin-bar/module.php (hunk 15 above)
Comment (matipojo) [reply modules/admin-bar/module.php:108]: It's not settings that are used on server side, it's a config for the client side.

File: modules/admin-bar/module.php (hunk 16 above)
Comment (matipojo) [reply modules/admin-bar/module.php:70]: As above it's settings for the client side.

**Review by matipojo — DISMISSED** [review]

File: modules/admin-bar/module.php (hunk 16 above)
Comment (matipojo) [reply modules/admin-bar/module.php:69]: @Nevoss use App->print_config( 'elementor-admin-bar' );

**Review by matipojo — APPROVED** [review]

**Review by kobizz — APPROVED** [review]
