### PR TITLE
Editor/Container: Fix - Custom repeater not working in columns/sectio…

### LINKED ISSUE #12242: Unable to delete column's & sections
I've ran into an issue with Elementor builder.

When I create new pages or go to edit a page.
Adding new sections/columns result in not allowing me to fully delete or adjust widgets.

Issues i've experienced.

Moving a widget creates 1-2 duplicates of the widget and moves it to a completely random spot
Deleting widgets don't delete the widget until editor is refreshed and the column is still there along with another widget

For example in a column I had social icons & an image. Deleting the column would only remove the image but not the social icons and the column alone.

It'd still show in the navigation bar and couldn't delete through navigation bar as well.

I've tried rolling back to previous versions of elementor but still broken as well.

### PR DESCRIPTION
**Pull request by iNewLegend**

### CODE REVIEW

File: assets/dev/js/editor/container/container.js [hunk 1]
```diff
@@ -224,15 +224,17 @@ export default class Container extends ArgsObject {
...
-		const repeaters = Object.values( this.controls ).filter( ( control ) => 'repeater' === control.type );
-
-		if ( 1 === repeaters.length ) {
-			Object.defineProperty( this, 'children', {
-				get() {
-					elementorCommon.helpers.softDeprecated( 'children', '3.0.0', 'container.repeaters[ repeaterName ].children' );
-					return this.repeaters[ repeaters[ 0 ].name ].children;
-				},
-			} );
+		if ( [ 'widget', 'document' ].indexOf( this.type ) > -1 ) {
```
Comment (matipojo) [inline assets/dev/js/editor/container/container.js:227]: Yoda condition.

**Review by matipojo — CHANGES_REQUESTED** [review]

File: assets/dev/js/editor/container/container.js (hunk 1 above)
Comment (iNewLegend) [reply assets/dev/js/editor/container/container.js]: Handled, force-pushed.

**Review by matipojo — APPROVED** [review]

**Review by matipojo — APPROVED** [review]

**Review by kobizz — APPROVED** [review]
