### PR TITLE
Utils/ReplaceURL: Fix - Page settings -> Background images does not replaced. ED-1334, ED-1630

### LINKED ISSUE #10382: Elementor Pro: Custom fonts file URLS are static and are not changed when using URL-Replacer
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.
## Description
When creating a custom font, Elementor Pro links the fonts with a static url. When changing URL it is not affected by Elementors own URL-Replacer, that for with every domain change, the links break. The only way to fix this as the moment, is to delete each font-file link and readd them, after the new URL has been defined

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

### PR DESCRIPTION
**Pull request by iNewLegend**
Prepare to fix #10382

### CODE REVIEW

File: includes/utils.php [hunk 1]
```diff
@@ -128,10 +130,21 @@ public static function replace_urls( $from, $to ) {
 			"WHERE `meta_key` = '_elementor_data' AND `meta_value` LIKE '[%' ;" ); // meta_value LIKE '[%' are json formatted
 		// @codingStandardsIgnoreEnd
 
+		$second_rows_affected = $wpdb->query(
+			"UPDATE {$wpdb->postmeta} " .
+			$wpdb->prepare( 'SET `meta_value` = REPLACE(`meta_value`, %s, %s) ', $from, $to ) .
+			'WHERE `meta_key` = \'' . Manager::META_KEY . '\''
+		);
+
+		$rows_affected = false === $second_rows_affected ? false : $rows_affected + $second_rows_affected;
```
Comment (matipojo) [inline includes/utils.php:139]: The second query shouldn't break the action.
```suggestion
		if ( $second_rows_affected ) {
			$rows_affected += $second_rows_affected;
		}
```

**Review by matipojo — CHANGES_REQUESTED** [review]
Nice Work!

File: includes/utils.php (hunk 1 above)
Comment (iNewLegend) [reply includes/utils.php]: Handled.

**Review by matipojo — APPROVED** [review]

**Review by kobizz — APPROVED** [review]
