### PR TITLE
Video Widget: Fix - Due to a Youtube Embed API bug, when there are tw… (ED-1902)

### LINKED ISSUE #13711: YouTube player element ID required.
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

Since last version (3.1) in the pages that includes the video widget, Elementor shows the following error on the console:

`www-widgetapi.js:638 Uncaught Error: YouTube player element ID required.
    at new Z (www-widgetapi.js:638)
    at Video.prepareYTVideo (video.cadfb803f731eda62363.bundle.min.js:2)
    at video.cadfb803f731eda62363.bundle.min.js:2
    at YoutubeLoader.onApiReady (frontend.min.js:2)
    at frontend.min.js:2`

### PR DESCRIPTION
**Pull request by udidol**
…o (or more) videos on the same page, while one has Privacy Mode on and the other does not, the second video will not work properly. This problem occurs only when Optimized Assets Loading is off.

Fixes #13711.

## PR Type
What kind of change does this PR introduce?

- [X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

* Video Widget; Fix - When there are two videos in a single page, while one of them has Privacy mode on, the second video does not work properly.

## Quality assurance

- [X] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

### CODE REVIEW

**Review by kobizz — DISMISSED** [review]

File: assets/dev/js/frontend/handlers/video.js [hunk 1]
```diff
@@ -133,7 +133,17 @@ export default class Video extends elementorModules.frontend.handlers.Base {
 			return;
 		}
 
-		this.apiProvider.onApiReady( ( apiObject ) => this.prepareYTVideo( apiObject ) );
+		// When Optimized asset loading is set to off, the video type is set to 'Youtube', and 'Privacy Mode' is set
+		// to 'On', there might be a conflict with other videos that are loaded WITHOUT privacy mode, such as a
+		// video bBackground in a section. In these cases, to avoid the conflict, a timeout is added to postpone the
```
Comment (matipojo) [inline assets/dev/js/frontend/handlers/video.js:138]:
```suggestion
		// video background in a section. In these cases, to avoid the conflict, a timeout is added to postpone the
```

File: assets/dev/js/frontend/handlers/video.js [hunk 2]
```diff
@@ -133,7 +133,17 @@ export default class Video extends elementorModules.frontend.handlers.Base {
...
+		// initialization of the Youtube API object.
+		if ( ! elementorFrontend.config.experimentalFeatures[ 'e_optimized_assets_loading' ] && elementSettings.yt_privacy ) {
+			setTimeout( () => {
```
Comment (matipojo) [inline assets/dev/js/frontend/handlers/video.js:141]: You can always defer the loading, even if the feature is on.

**Review by matipojo — CHANGES_REQUESTED** [review]

File: assets/dev/js/frontend/handlers/video.js (hunk 1 above)
Comment (udidol) [reply assets/dev/js/frontend/handlers/video.js:138]: nice catch

Comment (udidol) [reply assets/dev/js/frontend/handlers/video.js:138]: Done.

File: assets/dev/js/frontend/handlers/video.js (hunk 2 above)
Comment (udidol) [reply assets/dev/js/frontend/handlers/video.js:141]: Done.

**Review by matipojo — DISMISSED** [review]

File: assets/dev/js/frontend/handlers/section/background-video.js [hunk 3]
```diff
@@ -194,7 +192,17 @@ export default class BackgroundVideo extends elementorModules.frontend.handlers.
 				rel: 0,
 				playsinline: 1,
 			},
-		} );
+		};
+
+		// To handle CORS issues, when the default host is changed, the origin parameter has to be set.
+		if ( elementSettings.background_privacy_mode ) {
+			playerOptions.host = 'http://www.youtube-nocookie.com';
```
Comment (kobizz) [inline assets/dev/js/frontend/handlers/section/background-video.js:199]:
```suggestion
			playerOptions.host = 'https://www.youtube-nocookie.com';
```

File: assets/dev/js/frontend/handlers/video.js [hunk 4]
```diff
@@ -133,7 +134,13 @@ export default class Video extends elementorModules.frontend.handlers.Base {
 			return;
 		}
 
-		this.apiProvider.onApiReady( ( apiObject ) => this.prepareYTVideo( apiObject ) );
+		// Due to a bug in the YouTube Embed API, there might be a conflict when privacy mode is set to ON, and the
+		// page contains additional YouTube videos that are loaded WITHOUT privacy mode, such as a video background
+		// in a section. In these cases, to avoid the conflict, a timeout is added to defer the initialization of
+		// the Youtube API object.
+		setTimeout( () => {
```
Comment (kobizz) [inline assets/dev/js/frontend/handlers/video.js:141]: Set timeout only when "improved assets loading" is disabled

**Review by kobizz — CHANGES_REQUESTED** [review]

File: assets/dev/js/frontend/handlers/video.js (hunk 4 above)
Comment (udidol) [reply assets/dev/js/frontend/handlers/video.js]: Done.

File: assets/dev/js/frontend/handlers/section/background-video.js (hunk 3 above)
Comment (udidol) [reply assets/dev/js/frontend/handlers/section/background-video.js]: Done.

**Review by kobizz — APPROVED** [review]
