### PR TITLE
Fix: Page is not loading due to errors in the deprecation module (#19390, #19562) [ED-8031]

### LINKED ISSUE #19390: 🐞 Bug report:
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

After updating the Elementor plugin with the latest version 3.7.0, which was recently released, the Elementor tool doesn't load at all. Keeps on loading during initial grey screen. 

This happens both in Normal Mode and Safe Mode.

In the Console there are 2 main errors appearing:

1) 2022-08-08 15:33:17 [error X 8][https://studyyoga.com/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=3.7.0:2:4155] elementorDevTools is not defined 
2) 2022-08-08 15:50:30 [error X 2][https://studyyoga.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.0:3:872751] elementorFrontend is not defined 

From before the update and after the update nothing has been done to the website, no additional code nor elements.

Also tried removing all plugins and custom code, but it doesn't solve the issue.
Checked on the Linux server for latest updates and PHP version: everything runs ok.

Main issue in the latest update.

Any ideas? We need to proceed with the website development, so the issue is quite urgent! Thank you.

### Steps to reproduce

After updating the Elementor plugin with the latest version 3.7.0, which was recently released, the Elementor tool doesn't load at all. Keeps on loading during initial grey screen. 

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.41 (Ubuntu)
	MySQL version: (Ubuntu) v8.0.30
	PHP Version: 7.4.3
	PHP Memory Limit: 128M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 64M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.1
	Site URL: https://studyyoga.com
	Home URL: https://studyyoga.com
	WP Multisite: No
	Max Upload Size: 56 MB
	Memory limit: 2048M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 0
	Admin Email: contact@dezea.digital
	Debug Mode: Inactive

== Theme ==
	Name: BuddyBoss Child
	Version: 1.0.1
	Author: BuddyBoss.com
	Child Theme: Yes
	Parent Theme Name: BuddyBoss Theme
	Parent Theme Version: 2.0.7
	Parent Theme Author: BuddyBoss

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36

== Active Plugins ==
	Auto Login on Register for BuddyBoss
		Version: 1.0.0
		Author: Xavier Lopez

	BuddyBoss Platform
		Version: 2.0.7
		Author: BuddyBoss

	BuddyBoss Platform Pro
		Version: 2.0.5
		Author: BuddyBoss

	Elementor
		Version: 3.7.0
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.3
		Author: Elementor.com

	ImageMagick Engine
		Version: 1.7.4
		Author: Orangelab

	LearnDash HUB
		Version: 1.0.0
		Author: LearnDash

	LearnDash LMS
		Version: 4.3.0.2
		Author: LearnDash

	LearnDash LMS - Elementor
		Version: 1.0.3
		Author: LearnDash

	LearnDash LMS - ProPanel
		Version: 2.1.4.1
		Author: LearnDash

	WPCode - Insert Headers, Footers, and Code Snippets
		Version: 2.0.1
		Author: WPCode

== Must-Use Plugins ==
	Elementor Safe Mode
		Version: 1.0.0
		Author: Elementor.com

== Elementor Experiments ==
	Optimized DOM Output: Inactive
	Improved Asset Loading: Inactive
	Improved CSS Loading: Inactive
	Inline Font Icons: Inactive
	Accessibility Improvements: Inactive
	Additional Custom Breakpoints: Active
	Import Export Template Kit: Inactive
	Hide native WordPress widgets from search results: Inactive
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Default to New Theme Builder: Active by default
	Landing Pages: Inactive
	Color Sampler: Inactive
	Favorite Widgets: Inactive
	Admin Top Bar: Inactive
	Page Transitions: Active by default
	Notes: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
Log: showing 20 of 262022-07-03 23:33:47 [info] elementor::elementor_updater Started 
2022-07-03 23:33:47 [info] Elementor/Upgrades - _on_each_version Start  
2022-07-03 23:33:47 [info] Elementor/Upgrades - _on_each_version Finished 
2022-07-03 23:33:47 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.6',
  'to' => '3.6.7',
)]
2022-07-03 23:33:47 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.6',
  'to' => '3.6.7',
)]
2022-07-27 23:33:49 [info] elementor::elementor_updater Started 
2022-07-27 23:33:49 [info] Elementor/Upgrades - _on_each_version Start  
2022-07-27 23:33:49 [info] Elementor/Upgrades - _on_each_version Finished 
2022-07-27 23:33:49 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.7',
  'to' => '3.6.8',
)]
2022-07-27 23:33:49 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.7',
  'to' => '3.6.8',
)]
2022-08-01 11:33:48 [info] elementor-pro::elementor_pro_updater Started 
2022-08-01 11:33:48 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-08-01 11:33:48 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-08-01 11:33:48 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.2',
  'to' => '3.7.3',
)]
2022-08-01 11:33:48 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.7.2',
  'to' => '3.7.3',
)]
2022-08-08 11:33:55 [info] elementor::elementor_updater Started 
2022-08-08 11:33:55 [info] Elementor/Upgrades - _on_each_version Start  
2022-08-08 11:33:55 [info] Elementor/Upgrades - _on_each_version Finished 
2022-08-08 11:33:55 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.8',
  'to' => '3.7.0',
)]
2022-08-08 11:33:56 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.8',
  'to' => '3.7.0',
)]

PHP: showing 9 of 9PHP: 2022-06-19 14:58:21 [error X 1][/var/www/studyyoga.com/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::294] Uncaught Error: Call to a member function update_meta() on null in /var/www/studyyoga.com/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:294
Stack trace:
#0 /var/www/studyyoga.com/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions()
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions()
#2 /var/www/studyyoga.com/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func()
#3 /var/www/studyyoga.com/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request()
#4 /var/www/studyyoga.com/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#5 /var/www/studyyoga.com/wp-includes/plugin.php(476): WP_Hook->do_action()
#6 /var/www/studyyoga.com/wp-admin/admin-ajax.php(187): do_action()
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-06-20 17:56:33 [error X 4][/var/www/studyyoga.com/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php::294] Uncaught Error: Call to a member function update_meta() on bool in /var/www/studyyoga.com/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php:294
Stack trace:
#0 /var/www/studyyoga.com/wp-content/plugins/elementor-pro/modules/theme-builder/classes/conditions-manager.php(167): ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->save_conditions()
#1 [internal function]: ElementorPro\Modules\ThemeBuilder\Classes\Conditions_Manager->ajax_save_theme_template_conditions()
#2 /var/www/studyyoga.com/wp-content/plugins/elementor/core/common/modules/ajax/module.php(171): call_user_func()
#3 /var/www/studyyoga.com/wp-includes/class-wp-hook.php(307): Elementor\Core\Common\Modules\Ajax\Module->handle_ajax_request()
#4 /var/www/studyyoga.com/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#5 /var/www/studyyoga.com/wp-includes/plugin.php(476): WP_Hook->do_action()
#6 /var/www/studyyoga.com/wp-admin/admin-ajax.php(187): do_action()
#7 {main}
  thrown [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-06-21 15:58:41 [notice X 1][/var/www/studyyoga.com/wp-content/plugins/elementor/includes/managers/image.php::87] Trying to access array offset on value of type bool [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-06-22 14:04:12 [notice X 2137][/var/www/studyyoga.com/wp-content/plugins/elementor-pro/modules/nav-menu/widgets/nav-menu.php::1483] Trying to access array offset on value of type null [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-01 10:29:16 [notice X 35][/var/www/studyyoga.com/wp-content/plugins/elementor-pro/modules/nav-menu/widgets/nav-menu.php::1446] Trying to access array offset on value of type null [array (
  'trace' => '
#0: /var/www/studyyoga.com/wp-content/plugins/elementor-pro/modules/nav-menu/widgets/nav-menu.php(1446): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /var/www/studyyoga.com/wp-content/plugins/elementor/includes/base/controls-stack.php(2221): ElementorPro\Modules\NavMenu\Widgets\Nav_Menu -> render()
#2: /var/www/studyyoga.com/wp-content/plugins/elementor/includes/base/widget-base.php(609): Elementor\Controls_Stack -> render_by_mode()
#3: /var/www/studyyoga.com/wp-content/plugins/elementor/includes/base/widget-base.php(750): Elementor\Widget_Base -> render_content()
#4: /var/www/studyyoga.com/wp-content/plugins/elementor/includes/base/element-base.php(447): Elementor\Widget_Base -> print_content()
',
)]
PHP: 2022-07-01 10:29:16 [notice X 35][/var/www/studyyoga.com/wp-content/plugins/elementor-pro/modules/nav-menu/widgets/nav-menu.php::1459] Trying to access array offset on value of type null [array (
  'trace' => '
#0: /var/www/studyyoga.com/wp-content/plugins/elementor-pro/modules/nav-menu/widgets/nav-menu.php(1459): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /var/www/studyyoga.com/wp-content/plugins/elementor/includes/base/controls-stack.php(2221): ElementorPro\Modules\NavMenu\Widgets\Nav_Menu -> render()
#2: /var/www/studyyoga.com/wp-content/plugins/elementor/includes/base/widget-base.php(609): Elementor\Controls_Stack -> render_by_mode()
#3: /var/www/studyyoga.com/wp-content/plugins/elementor/includes/base/widget-base.php(750): Elementor\Widget_Base -> render_content()
#4: /var/www/studyyoga.com/wp-content/plugins/elementor/includes/base/element-base.php(447): Elementor\Widget_Base -> print_content()
',
)]
PHP: 2022-07-01 10:29:16 [notice X 35][/var/www/studyyoga.com/wp-content/plugins/elementor-pro/modules/nav-menu/widgets/nav-menu.php::1470] Trying to access array offset on value of type null [array (
  'trace' => '
#0: /var/www/studyyoga.com/wp-content/plugins/elementor-pro/modules/nav-menu/widgets/nav-menu.php(1470): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /var/www/studyyoga.com/wp-content/plugins/elementor/includes/base/controls-stack.php(2221): ElementorPro\Modules\NavMenu\Widgets\Nav_Menu -> render()
#2: /var/www/studyyoga.com/wp-content/plugins/elementor/includes/base/widget-base.php(609): Elementor\Controls_Stack -> render_by_mode()
#3: /var/www/studyyoga.com/wp-content/plugins/elementor/includes/base/widget-base.php(750): Elementor\Widget_Base -> render_content()
#4: /var/www/studyyoga.com/wp-content/plugins/elementor/includes/base/element-base.php(447): Elementor\Widget_Base -> print_content()
',
)]
PHP: 2022-07-01 10:29:16 [notice X 35][/var/www/studyyoga.com/wp-content/plugins/elementor-pro/modules/nav-menu/widgets/nav-menu.php::1483] Trying to access array offset on value of type null [array (
  'trace' => '
#0: /var/www/studyyoga.com/wp-content/plugins/elementor-pro/modules/nav-menu/widgets/nav-menu.php(1483): Elementor\Core\Logger\Manager -> rest_error_handler()
#1: /var/www/studyyoga.com/wp-content/plugins/elementor/includes/base/controls-stack.php(2221): ElementorPro\Modules\NavMenu\Widgets\Nav_Menu -> render()
#2: /var/www/studyyoga.com/wp-content/plugins/elementor/includes/base/widget-base.php(609): Elementor\Controls_Stack -> render_by_mode()
#3: /var/www/studyyoga.com/wp-content/plugins/elementor/includes/base/widget-base.php(750): Elementor\Widget_Base -> render_content()
#4: /var/www/studyyoga.com/wp-content/plugins/elementor/includes/base/element-base.php(447): Elementor\Widget_Base -> print_content()
',
)]
PHP: 2022-08-08 15:32:58 [notice X 3][/var/www/studyyoga.com/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

JS: showing 7 of 7JS: 2022-06-20 11:55:12 [error X 77][https://studyyoga.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.6:2:421003] Cannot read properties of undefined (reading \'get\') 
JS: 2022-06-20 12:07:07 [error X 11][https://studyyoga.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.6:2:516092] Cannot read properties of null (reading \'getBoundingClientRect\') 
JS: 2022-06-26 15:48:46 [error X 36][https://studyyoga.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.6:2:459676] Cannot read properties of null (reading \'toLowerCase\') 
JS: 2022-06-28 11:55:03 [error X 2][https://studyyoga.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.6.6:2:362278] Cannot read properties of undefined (reading \'isEditable\') 
JS: 2022-06-28 13:46:38 [error X 1][https://studyyoga.com/wp-content/plugins/elementor-pro/assets/lib/sticky/jquery.sticky.min.js?ver=3.7.2:1:741] Failed to execute \'getComputedStyle\' on \'Window\': parameter 1 is not of type \'Element\'. 
JS: 2022-08-08 15:33:17 [error X 8][https://studyyoga.com/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=3.7.0:2:4155] elementorDevTools is not defined 
JS: 2022-08-08 15:50:30 [error X 2][https://studyyoga.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.7.0:3:872751] elementorFrontend is not defined 

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible
	LearnDash LMS - Elementor: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

### LINKED ISSUE #19562: 🐞 Bug report: Needs handling for the soft deprecations since v3.7.0
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest development version of Elementor.

### Description

So In the v3.7.0 some soft action hooks are deprecated,  one of the key deprecation is ''elementor/widgets/widgets_registered'' action is now 'elementor/widgets/register' , however many plugins are still using the old action. Which adds elementorDevToolsConfig.deprecation.soft_notices
 to populate but in the recent live versions. when elementor PRO is activated it shows up this error in browsers console on editor. 
 
 dev-tools.js?ver=3.8.0-dev4:508 Uncaught TypeError: Cannot read properties of undefined (reading 'deprecated')
    at dev-tools.js?ver=3.8.0-dev4:508:49
    at Array.forEach (<anonymous>)
    at Module.notifyBackendDeprecations (dev-tools.js?ver=3.8.0-dev4:501:31)
    at new Module (dev-tools.js?ver=3.8.0-dev4:491:10)
    at dev-tools.js?ver=3.8.0-dev4:534:30
    at dev-tools.js?ver=3.8.0-dev4:537:3
    at dev-tools.js?ver=3.8.0-dev4:539:12
(anonymous) @ dev-tools.js?ver=3.8.0-dev4:508
notifyBackendDeprecations @ dev-tools.js?ver=3.8.0-dev4:501
Module @ dev-tools.js?ver=3.8.0-dev4:491
(anonymous) @ dev-tools.js?ver=3.8.0-dev4:534
(anonymous) @ dev-tools.js?ver=3.8.0-dev4:537
(anonymous) @ dev-tools.js?ver=3.8.0-dev4:539
editor-document.js?ver=3.8.0-dev4:1877 Uncaught ReferenceError: elementorDevTools is not defined
    at get CommandHistory [as CommandHistory] (editor-document.js?ver=3.8.0-dev4:1877:5)
    at ../modules/global-widget/assets/js/editor/commands/link.js (editor.js?ver=3.8.0-dev36:3622:23)
    at __webpack_require__ (editor.js?ver=3.8.0-dev36:19491:41)
    at ../modules/global-widget/assets/js/editor/commands/index.js (editor.js?ver=3.8.0-dev36:3493:13)
    at __webpack_require__ (editor.js?ver=3.8.0-dev36:19491:41)
    at ../modules/global-widget/assets/js/editor/component.js (editor.js?ver=3.8.0-dev36:3843:40)
    at __webpack_require__ (editor.js?ver=3.8.0-dev36:19491:41)
    at ../modules/global-widget/assets/js/editor/module.js (editor.js?ver=3.8.0-dev36:4912:41)
    at __webpack_require__ (editor.js?ver=3.8.0-dev36:19491:41)
    at editor.js?ver=3.8.0-dev36:19727:39
    
Since this error triggers prior to loading elementordevtools, making it undefined. 
This error also cause elementorDevTools to not load properly and hence shows up further errors if anywhere elementorDevTools is utilized. 

    
    

### Steps to reproduce

To reproduce, user elementor 3.7.0 or greater and elementor pro 3.7.3 use any plugin that could trigger the soft deprecation. of 'elementor/widgets/widgets_registered' and you could see the issue in editor. 

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro) with development versions.
- [X] This bug happens with a vanilla WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Linux
	Software: nginx/1.18.0
	MySQL version: (Ubuntu) v8.0.30
	PHP Version: 7.3.27-9+ubuntu20.04.1+deb.sury.org+1
	PHP Memory Limit: 128M
	PHP Max Input Vars: 6000
	PHP Max Post Size: 32M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.1
	Site URL: https://aero.bwfdemo.in
	Home URL: https://aero.bwfdemo.in
	WP Multisite: No
	Max Upload Size: 32 MB
	Memory limit: 40M
	Max Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-US
	Timezone: 5.5
	Admin Email: harish@wisetr.com
	Debug Mode: Active

== Theme ==
	Name: Hello Elementor
	Version: 2.6.1
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36

== Active Plugins ==
	Autonami Marketing Automations For WordPress
		Version: 2.1.4.beta.fix-1753
		Author: BuildWooFunnels

	Autonami Marketing Automations Pro
		Version: 2.1.3
		Author: WooFunnels

	Elementor
		Version: 3.7.2
		Author: Elementor.com

	Elementor Pro
		Version: 3.7.3
		Author: Elementor.com

	WooCommerce
		Version: 6.8.0
		Author: Automattic

	WooFunnels Funnel Builder
		Version: 2.3.0
		Author: BuildWooFunnels

	WooFunnels Funnel Builder Pro
		Version: 2.3.4
		Author: BuildWooFunnels

	WP File Manager
		Version: 7.1.6
		Author: mndpsingh287

== Must-Use Plugins ==
	Health Check Troubleshooting Mode
		Version: 1.7.2
		Author: 

	LearnDash LMS Multisite
		Version: 1.0.0
		Author: LearnDash

== Elements Usage ==
	
	page : 32
		button : 5
		divider : 4
		heading : 59
		icon-list : 1
		image : 13
		shortcode : 1
		text-editor : 4
		video : 1
	wp-post : 1
		accordion : 3
		button : 74
		divider : 90
		heading : 1492
		icon : 86
		icon-box : 66
		icon-list : 196
		image : 511
		image-box : 6
		image-carousel : 4
		image-gallery : 3
		menu-anchor : 3
		progress : 2
		shortcode : 1
		spacer : 76
		star-rating : 62
		testimonial : 12
		text-editor : 228
		toggle : 2
		video : 50
		wfocu-accept-offer-button : 35
		wfocu-offer-price : 8
		wfocu-offer-product-title : 7
		wfocu-offer-reject-button : 1
		wfocu-offer-reject-link : 31
		wfocu-product-images : 7
		wfocu-qty-selector : 5
		wfocu-short-description : 1
		wfocu-variation-selector : 10
		wfty-customer-detail : 1
		wfty-order-detail : 1
	wp-page : 21
		heading : 2
		image : 2
		text-editor : 2

== Elementor Experiments ==
	Optimized DOM Output: Inactive by default
	Improved Asset Loading: Inactive by default
	Improved CSS Loading: Inactive by default
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Inactive by default
	Additional Custom Breakpoints: Inactive by default
	Import Export Template Kit: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Default to New Theme Builder: Active by default
	Hello Theme Header & Footer: Inactive by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Notes: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	
JS: showing 2 of 2JS: 2022-05-11 11:37:13 [error X 3][https://aero.bwfdemo.in/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=3.6.5:2:30599] Cannot read properties of undefined (reading \'model\') 
JS: 2022-08-17 14:01:13 [error X 20][https://aero.bwfdemo.in/wp-content/plugins/elementor/assets/js/editor-document.min.js?ver=3.7.1:2:25976] elementorDevTools is not defined 

Log: showing 20 of 302022-07-28 11:12:30 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.7',
  'to' => '3.6.8',
)]
2022-07-28 11:12:31 [info] elementor::elementor_updater Started 
2022-07-28 11:12:31 [info] Elementor/Upgrades - _on_each_version Start  
2022-07-28 11:12:32 [info] Elementor/Upgrades - _on_each_version Finished 
2022-07-28 11:12:32 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.7',
  'to' => '3.6.8',
)]
2022-08-09 16:03:44 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.8',
  'to' => '3.7.0',
)]
2022-08-09 16:03:44 [info] elementor::elementor_updater Started 
2022-08-09 16:03:44 [info] Elementor/Upgrades - _on_each_version Start  
2022-08-09 16:03:46 [info] Elementor/Upgrades - _on_each_version Finished 
2022-08-09 16:03:46 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.6.8',
  'to' => '3.7.0',
)]
2022-08-14 21:35:20 [info] elementor::elementor_updater Started 
2022-08-14 21:35:20 [info] Elementor/Upgrades - _on_each_version Start  
2022-08-14 21:35:20 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.0',
  'to' => '3.7.1',
)]
2022-08-14 21:35:21 [info] Elementor/Upgrades - _on_each_version Finished 
2022-08-14 21:35:21 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.0',
  'to' => '3.7.1',
)]
2022-08-14 21:35:22 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '3.7.0',
  'to' => '3.7.1',
)]
2022-08-22 12:35:31 [info] elementor-pro::elementor_pro_updater Started 
2022-08-22 12:35:31 [info] Elementor Pro/Upgrades - _on_each_version Start  
2022-08-22 12:35:31 [info] Elementor Pro/Upgrades - _on_each_version Finished 
2022-08-22 12:35:31 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.5.1',
  'to' => '3.7.3',
)]

PHP: showing 10 of 10PHP: 2022-06-21 12:42:04 [notice X 1][/home/ubuntu/public_html/bwfdemo-aero/wp-content/plugins/elementor-pro/license/updater.php::84] Undefined index: new_version [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-06-21 14:51:12 [notice X 1][/home/ubuntu/public_html/bwfdemo-aero/wp-content/plugins/elementor/modules/landing-pages/module.php::127] Trying to get property 'post_type' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-01 16:30:02 [notice X 2][/home/ubuntu/public_html/bwfdemo-aero/wp-content/plugins/elementor/includes/managers/image.php::34] Undefined index: size [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-03 09:47:51 [error X 1][/home/ubuntu/public_html/bwfdemo-aero/wp-content/plugins/elementor/core/files/css/base.php::896] Allowed memory size of 134217728 bytes exhausted (tried to allocate 40960 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-04 19:32:19 [error X 3][/home/ubuntu/public_html/bwfdemo-aero/wp-content/plugins/elementor/includes/base/controls-stack.php::2127] Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-21 14:01:55 [error X 1][/home/ubuntu/public_html/bwfdemo-aero/wp-content/plugins/elementor/includes/base/element-base.php::450] Allowed memory size of 134217728 bytes exhausted (tried to allocate 24576 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-25 03:13:27 [error X 1][/home/ubuntu/public_html/bwfdemo-aero/wp-content/plugins/elementor-pro/modules/woocommerce/widgets/purchase-summary.php::970] Allowed memory size of 134217728 bytes exhausted (tried to allocate 131072 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-26 17:02:53 [error X 1][/home/ubuntu/public_html/bwfdemo-aero/wp-content/plugins/elementor/core/common/modules/ajax/module.php::265] Allowed memory size of 134217728 bytes exhausted (tried to allocate 9721144 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-07-30 15:39:35 [error X 1][/home/ubuntu/public_html/bwfdemo-aero/wp-content/plugins/elementor/includes/base/element-base.php::450] Allowed memory size of 134217728 bytes exhausted (tried to allocate 81920 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2022-08-22 12:34:47 [notice X 7][/home/ubuntu/public_html/bwfdemo-aero/wp-content/plugins/elementor/core/base/document.php::250] Trying to get property 'ID' of non-object [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatible
	WooFunnels Funnel Builder: Incompatible
	WooFunnels Funnel Builder Pro: Incompatible

== Elementor Pro - Compatibility Tag ==

### PR DESCRIPTION
**Pull request by StyleShit**
closes #19390 
closes #19562

### CODE REVIEW

File: modules/dev-tools/assets/js/index.js [hunk 1]
```diff
@@ -0,0 +1,10 @@
+import Deprecation from './deprecation';
```
Comment (udidol) [inline modules/dev-tools/assets/js/index.js:1]: Why do you need this file? What advantage does it give you that you cannot do by making small changes to `module.js`?

**Review by udidol — CHANGES_REQUESTED** [review]

File: modules/dev-tools/assets/js/index.js (hunk 1 above)
Comment (matipojo) [reply modules/dev-tools/assets/js/index.js:1]: Creating an instance of a class should be in a separated file

**Review by udidol — APPROVED** [review]
