### PR TITLE
Fix: Elementor posts aren't properly imported with WordPress Importer v0.7

### LINKED ISSUE #11466: Native wordpress import/export does not work
Hello,

as the title says, the native wordpress import/export does not work for pages created by elementor.  Am I missing something.  Isn't elementor supposed to be compatible with the native wordpress builder?

**Steps to reproduce**
1. Create a page with elementor
2. Tools > Export the full site/content
3. Import to another domain/wordpress install using the native wordpress importer (Tools > Import)
4. Layout is broken

I searched for similar issues but could not find any help.  This has been tested on a fresh install with no plugins and the default theme.

**EDIT**
There is something wrong with the __elementor_data_ meta field.

On the export file the elementor_data field is the following:
`[{"id":"cf381fa","elType":"section","settings":{"structure":"20"},"elements": ....`

After the import on a new site it has backslashes on it:
`[{\"id\":\"cf381fa\",\"elType\":\"section\",\"settings\":{\"structure\":\"20\"},\"elements\":`

Thats the reason why it is not displaying the elementor structure of the page.  How to solve that.  Am I missing something?

### PR DESCRIPTION
**Pull request by udidol**
Added a check for the WP Importer version - if it is at least 0.7, it will not wp_slash the '_elementor_data' contents

Fixes #11466 #10774 

## PR Type
What kind of change does this PR introduce?

- [X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

* Fix: Elementor posts aren't properly imported when using the WordPress Importer v0.7 and above

## Test instructions
This PR can be tested by following these steps:

* Export a post, then import it without the fix. Make sure it is imported badly.
* Import the same post with the fix. Make sure it is imported correctly.

### CODE REVIEW

File: includes/compatibility.php [hunk 1]
```diff
@@ -333,6 +333,18 @@ public static function save_polylang_meta( $keys, $sync, $from, $to ) {
 	 * @return array Updated post meta.
 	 */
 	public static function on_wp_import_post_meta( $post_meta ) {
+		$wp_importer = get_plugins( '/wordpress-importer' );
+
+		if ( ! empty( $wp_importer ) ) {
+			$wp_importer_version = $wp_importer['wordpress-importer.php']['Version'];
+
+			if ( isset( $wp_importer_version ) && ! empty( $wp_importer_version ) ) {
```
Comment (matipojo) [inline includes/compatibility.php:341]:
```suggestion
			if ( ! empty( $wp_importer_version ) ) {
```
`! empty` includes `isset`.

**Review by matipojo — CHANGES_REQUESTED** [review]

**Review by matipojo — APPROVED** [review]
