### PR TITLE
Fix: WP CLI - Only 100 sites are processed when running on a multisite [ED-7834] (Fixes #18639)

### LINKED ISSUE #18639: 🐞 Bug report: Only the first 100 sites are processed by default usage of `get_sites()`
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

There's an issue in your code when iterating over sites in a multisite. A little known thing about the [`get_sites()`](https://developer.wordpress.org/reference/functions/get_sites/) function, is that the `WP_Site_Query` powering it, takes a `number` argument is used as the total number of sites to fetch from the database. [This `number` argument defaults to **100**](https://github.com/WordPress/wordpress-develop/blob/44cd1981b967966e22f4e40fa1ab04ee3ce2f728/src/wp-includes/class-wp-site-query.php#L127).

Because of this, most cli commands you provide for doing maintenance and automation after deployments will currently only process the first 100 sites. This includes things like:
- database upgrades
- flush_css commands
- cloud library syncs
- ...

**Currently, it's being used in these places:**

- https://github.com/elementor/elementor/blob/a4ba3cdece9dfd52b28acd55fc110be39a4e49da/includes/maintenance.php#L39
- https://github.com/elementor/elementor/blob/2cd3d50d8d87edde9cd3c820f5a0f8b1f2c4f24f/modules/wp-cli/update.php#L47
- https://github.com/elementor/elementor/blob/9aadba35a9ad52cd5e9cbef55a5761f47403491c/core/experiments/wp-cli.php#L128
- https://github.com/elementor/elementor/blob/2cd3d50d8d87edde9cd3c820f5a0f8b1f2c4f24f/modules/wp-cli/command.php#L41
- https://github.com/elementor/elementor/blob/15f9a99db9b35d63358f26ebd46ed7c7b6f45d68/modules/wp-cli/library.php#L45

A quick fix would be to pass in `['number' => 0]` for `$args`, but it might be better to get the total blog count with `get_blog_count()` and iterate over all sites in chunks :)

### Steps to reproduce

1. Find or create a multisite network that has over 100 active sites.
2. Open up a wp cli shell: `wp shell`
3. Run `count(get_sites());`

```bash
 $ wp shell
wp> count(get_sites());
=> int(100)
```

If we pass in the `number` argument, and set it to zero, we can see that the actual number of sites returned is bigger.
```bash
wp shell
wp> count(get_sites(['number' => 0]));
=> int(213)
```

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

NULL

### PR DESCRIPTION
**Pull request by vdwijngaert**
## PR Checklist

- [X] The commit message follows our guidelines:  https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

* While running CLI commands in a multisite environment, process all sites instead of only the first 100

## Description
This fix addresses issue #18639 where all multisite-related commands only loop over the first 100 sites, due to the default value of the `number` argument for the `WP_Site_Query` used by the `get_sites` function.

Since we only ever use the `blog_id`, I've limited the results to being an array of `blog_id`s as well, so we don't clog up the memory with `WP_Site` objects that remain unused.

## Test instructions
This PR can be tested by following these steps:

* Have a multisite with more than 100 blogs in it.
* Run any of the commands that call `get_sites`
* See that all sites are now getting processed instead of just the first 100.

## Quality assurance

- [X] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

Fixes #18639

### CODE REVIEW

File: core/experiments/wp-cli.php [hunk 1]
```diff
@@ -124,13 +124,9 @@ private function is_network( $assoc_args ) {
 	 * @return void
 	 */
 	private function foreach_sites( callable $callback ) {
-		/** @var \WP_Site[] $sites */
-		$sites = get_sites();
-
-		foreach ( $sites as $keys => $site ) {
-			// Cast $blog as an array instead of object
-			$blog_id = $site->blog_id;
+		$blog_ids = get_sites( [ 'fields' => 'ids', 'number' => 0 ] );
```
Comment (matipojo) [inline core/experiments/wp-cli.php:127]: Hi, Thanks for the fix!

Can you please extract it to a method for re-use?
```suggestion
		$blog_ids = $this->get_sites();
```

```
private function get_sites() { 
return get_sites(  [ 'fields' => 'ids', 'number' => 0 ]  );
```
```suggestion
		$blog_ids = get_sites( [ 'fields' => 'ids', 'number' => 0 ] );
```

**Review by matipojo — CHANGES_REQUESTED** [review]

File: core/experiments/wp-cli.php (hunk 1 above)
Comment (vdwijngaert) [reply core/experiments/wp-cli.php:127]: Hi, sorry, must have missed this. I'll look into it.

Comment (vdwijngaert) [reply core/experiments/wp-cli.php:127]: Just looked into it, extracting it for re-use sure seems like a decent thing to do, but I don't think it's in scope of the original issue, I'm simply offering a bugfix here. Refactoring raises more questions and only complicates things (usage is spread over 5 files, and there doesn't seem to be an obvious central place to put this method). 

Can we please get this merged? We're well over 2 months since the initial report and PR.

Comment (matipojo) [reply core/experiments/wp-cli.php:127]: I agree, we can take it from here. 
Thanks for sending it!
I will merge it.

Comment (matipojo) [inline core/experiments/wp-cli.php:127]:
```suggestion
		$blog_ids = get_sites( [
			'fields' => 'ids',
			'number' => 0
		] );
```

File: includes/maintenance.php [hunk 2]
```diff
@@ -36,7 +36,7 @@ public static function activation( $network_wide ) {
 
 		if ( is_multisite() && $network_wide ) {
 			static::create_default_kit(
-				get_sites( [ 'fields' => 'ids' ] )
+				get_sites( [ 'fields' => 'ids', 'number' => 0 ] )
```
Comment (matipojo) [inline includes/maintenance.php:39]:
```suggestion
				get_sites( [
					'fields' => 'ids',
					'number' => 0
				] );
```

File: modules/wp-cli/command.php [hunk 3]
```diff
@@ -37,13 +37,9 @@ public function flush_css( $args, $assoc_args ) {
 		$network = ! empty( $assoc_args['network'] ) && is_multisite();
 
 		if ( $network ) {
-			/** @var \WP_Site[] $blogs */
-			$blogs = get_sites();
-
-			foreach ( $blogs as $keys => $blog ) {
-				// Cast $blog as an array instead of  object
-				$blog_id = $blog->blog_id;
+			$blog_ids = get_sites( [ 'fields' => 'ids', 'number' => 0 ] );
```
Comment (matipojo) [inline modules/wp-cli/command.php:40]:
```suggestion
			$blog_ids = get_sites( [
				'fields' => 'ids',
				'number' => 0
			] );
```

File: modules/wp-cli/library.php [hunk 4]
```diff
@@ -41,13 +41,9 @@ public function sync( $args, $assoc_args ) {
 		$network = isset( $assoc_args['network'] ) && is_multisite();
 
 		if ( $network ) {
-			/** @var \WP_Site[] $sites */
-			$sites = get_sites();
-
-			foreach ( $sites as $keys => $blog ) {
-				// Cast $blog as an array instead of  object
-				$blog_id = $blog->blog_id;
+			$blog_ids = get_sites( [ 'fields' => 'ids', 'number' => 0 ] );
```
Comment (matipojo) [inline modules/wp-cli/library.php:44]:
```suggestion
			$blog_ids = get_sites( [
				'fields' => 'ids',
				'number' => 0
			] );
```

File: modules/wp-cli/update.php [hunk 5]
```diff
@@ -43,13 +43,9 @@ public function db( $args, $assoc_args ) {
 		$network = ! empty( $assoc_args['network'] ) && is_multisite();
 
 		if ( $network ) {
-			/** @var \WP_Site[] $sites */
-			$sites = get_sites();
-
-			foreach ( $sites as $keys => $blog ) {
-				// Cast $blog as an array instead of  object
-				$blog_id = $blog->blog_id;
+			$blog_ids = get_sites( [ 'fields' => 'ids', 'number' => 0 ] );
```
Comment (matipojo) [inline modules/wp-cli/update.php:46]:
```suggestion
			$blog_ids = get_sites( [
				'fields' => 'ids',
				'number' => 0
			] );
```

**Review by matipojo — CHANGES_REQUESTED** [review]

File: includes/maintenance.php [hunk 6]
```diff
@@ -36,7 +36,10 @@ public static function activation( $network_wide ) {
 
 		if ( is_multisite() && $network_wide ) {
 			static::create_default_kit(
-				get_sites( [ 'fields' => 'ids' ] )
+				get_sites( [
+					'fields' => 'ids',
+					'number' => 0
+				] );
```
Comment (matipojo) [inline includes/maintenance.php:42]:
```suggestion
				get_sites( [
					'fields' => 'ids',
				] );
```

File: includes/maintenance.php [hunk 7]
```diff
@@ -36,7 +36,9 @@ public static function activation( $network_wide ) {
 
 		if ( is_multisite() && $network_wide ) {
 			static::create_default_kit(
-				get_sites( [ 'fields' => 'ids' ] )
+				get_sites( [
+					'fields' => 'ids',
+				] );
```
Comment (matipojo) [inline includes/maintenance.php:41]:
```suggestion
				] )
```

File: core/experiments/wp-cli.php [hunk 8]
```diff
@@ -124,13 +124,12 @@ private function is_network( $assoc_args ) {
...
 	private function foreach_sites( callable $callback ) {
-		/** @var \WP_Site[] $sites */
-		$sites = get_sites();
-
-		foreach ( $sites as $keys => $site ) {
-			// Cast $blog as an array instead of object
-			$blog_id = $site->blog_id;
+		$blog_ids = get_sites( [
+			'fields' => 'ids',
+			'number' => 0
```
Comment (matipojo) [inline core/experiments/wp-cli.php:129]:
```suggestion
			'number' => 0,
```

File: modules/wp-cli/command.php [hunk 9]
```diff
@@ -37,13 +37,12 @@ public function flush_css( $args, $assoc_args ) {
...
 		if ( $network ) {
-			/** @var \WP_Site[] $blogs */
-			$blogs = get_sites();
-
-			foreach ( $blogs as $keys => $blog ) {
-				// Cast $blog as an array instead of  object
-				$blog_id = $blog->blog_id;
+			$blog_ids = get_sites( [
+				'fields' => 'ids',
+				'number' => 0
```
Comment (matipojo) [inline modules/wp-cli/command.php:42]:
```suggestion
				'number' => 0,
```

File: modules/wp-cli/library.php [hunk 10]
```diff
@@ -41,13 +41,12 @@ public function sync( $args, $assoc_args ) {
...
 		if ( $network ) {
-			/** @var \WP_Site[] $sites */
-			$sites = get_sites();
-
-			foreach ( $sites as $keys => $blog ) {
-				// Cast $blog as an array instead of  object
-				$blog_id = $blog->blog_id;
+			$blog_ids = get_sites( [
+				'fields' => 'ids',
+				'number' => 0
```
Comment (matipojo) [inline modules/wp-cli/library.php:46]:
```suggestion
				'number' => 0,
```

File: modules/wp-cli/update.php [hunk 11]
```diff
@@ -43,13 +43,12 @@ public function db( $args, $assoc_args ) {
...
 		if ( $network ) {
-			/** @var \WP_Site[] $sites */
-			$sites = get_sites();
-
-			foreach ( $sites as $keys => $blog ) {
-				// Cast $blog as an array instead of  object
-				$blog_id = $blog->blog_id;
+			$blog_ids = get_sites( [
+				'fields' => 'ids',
+				'number' => 0
```
Comment (matipojo) [inline modules/wp-cli/update.php:48]:
```suggestion
				'number' => 0,
```

**Review by matipojo — CHANGES_REQUESTED** [review]

**Comment by matipojo** [comment]
Thanks, @vdwijngaert for your fix!

**Comment by vdwijngaert** [comment]
Thanks for getting on top of this, @matipojo!

File: includes/maintenance.php [hunk 12]
```diff
@@ -36,7 +36,9 @@ public static function activation( $network_wide ) {
 
 		if ( is_multisite() && $network_wide ) {
 			static::create_default_kit(
-				get_sites( [ 'fields' => 'ids' ] )
+				get_sites( [
+					'fields' => 'ids',
```
Comment (vdwijngaert) [inline includes/maintenance.php:40]: Hey, looks like one is still wrong, @matipojo ?
