### PR TITLE
Fix: Accordion and Toggle Title color & Typography being overridden by Theme Style fixes #10900

### LINKED ISSUE #10900: Accordion widget title font size cannot be changed
Hi,

At the moment there is no opportunity to change the Accordion  title font size in the widget settings: https://www.screencast.com/t/VJ4uOjA94won as the setting for the font size is applied for the icon only.

Elementor Version 2.9.6, Theme Hello Elementor.

Please fix it. Thank you!

### PR DESCRIPTION
**Pull request by udidol**
PT 450

## PR Type
What kind of change does this PR introduce?

- [X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

* Fix: Title color & Typography are being overridden by Theme Style - Accordion and Toggle widgets

## Quality assurance

- [X] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

### CODE REVIEW

File: includes/widgets/accordion.php [hunk 1]
```diff
@@ -316,7 +316,7 @@ protected function _register_controls() {
 			Group_Control_Typography::get_type(),
 			[
 				'name' => 'title_typography',
-				'selector' => '{{WRAPPER}} .elementor-accordion .elementor-tab-title',
+				'selector' => '{{WRAPPER}} .elementor-accordion .elementor-accordion-title',
```
Comment (matipojo) [inline includes/widgets/accordion.php]: What about backwards compatibility for custom CSS on `elementor-tab-title` selector?

**Review by matipojo — CHANGES_REQUESTED** [review]

File: includes/widgets/accordion.php (hunk 1 above)
Comment (udidol) [reply includes/widgets/accordion.php]: You are right. I will bring back that selector in addition

**Review by kobizz — DISMISSED** [review]

File: includes/widgets/accordion.php (hunk 1 above)
Comment (kobizz) [reply includes/widgets/accordion.php]: @matipojo What kind of backward compatibility is needed here? How can a 3rd party user be affected when we change these selectors?

Comment (matipojo) [reply includes/widgets/accordion.php]: If a user adds Custom CSS like this: 
```
selector .elementor-tab-title {
```
it will stop to work.

File: includes/widgets/toggle.php [hunk 2]
```diff
@@ -306,13 +306,14 @@ protected function _register_controls() {
...
 
+		// The title selector specificity is to override Theme Style
 		$this->add_control(
 			'title_color',
 			[
 				'label' => __( 'Color', 'elementor' ),
 				'type' => Controls_Manager::COLOR,
 				'selectors' => [
-					'{{WRAPPER}} .elementor-tab-title a, {{WRAPPER}} .elementor-toggle-icon' => 'color: {{VALUE}};',
+					'{{WRAPPER}} .elementor-toggle-title, {{WRAPPER}} .elementor-toggle-icon' => 'color: {{VALUE}};',
```
Comment (matipojo) [inline includes/widgets/toggle.php]: Don't remove the old class.

File: includes/widgets/toggle.php [hunk 3]
```diff
@@ -340,7 +341,7 @@ protected function _register_controls() {
 			Group_Control_Typography::get_type(),
 			[
 				'name' => 'title_typography',
-				'selector' => '{{WRAPPER}} .elementor-toggle .elementor-tab-title',
+				'selector' => '{{WRAPPER}} .elementor-toggle .elementor-toggle-title',
```
Comment (matipojo) [inline includes/widgets/toggle.php]: Don't remove the old class.

**Review by matipojo — CHANGES_REQUESTED** [review]

File: includes/widgets/accordion.php (hunk 1 above)
Comment (kobizz) [reply includes/widgets/accordion.php]: It WON'T stop to work. please note that he just removed a SELECTOR, not a CLASS

**Review by matipojo — DISMISSED** [review]

**Review by kobizz — APPROVED** [review]

**Review by matipojo — APPROVED** [review]

**Review by KingYes — APPROVED** [review]
