### PR TITLE
Fixed #12320 - Custom breakpoints has stopped working since v3.0.0

### LINKED ISSUE #12320: Breakpoints not working
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

The new breakpoints interface (at Site Settings > Layout > Breakpoints) does absolutely nothing when the numbers are changed from the default. Breakpoints are locked at default values of 768 and 1025 no matter what is entered in the fields.

I rolled back to Elementor 2.9.14 and Pro 2.10.3 and breakpoints functioned correctly again.

## Steps to reproduce

Type numbers into breakpoints fields. Regenerate CSS. Refresh page and watch as the breakpoints have no impact at all. Breakpoints are locked at default values of 768 and 1025.

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

Tested with two sites on Elementor 3.0.3 and Elementor Pro 3.0.1. Tested with WordPress 5.4.2 and WordPress 5.5. Tested with two different hosting environments (local running PHP 7.4.1 and Cloudways running PHP 7.4). Tested with Hello theme and Twenty Twenty theme.

## Environment

<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.25 (Debian)
	MySQL version: mariadb.org binary distribution v5.6.47-87.0
	PHP Version: 7.4.7
	PHP Max Input Vars: 2500
	PHP Max Post Size: 250M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.5
	Site URL: https://wordpress-418647-1456796.cloudwaysapps.com
	Home URL: https://wordpress-418647-1456796.cloudwaysapps.com
	WP Multisite: No
	Max Upload Size: 250 MB
	Memory limit: 256M
	Permalink Structure: /%postname%/
	Language: en-CA
	Timezone: America/Toronto
	Debug Mode: Inactive

== Theme ==
	Name: Hello Elementor Child
	Version: 1.0.0
	Author: Elementor Team
	Child Theme: Yes
	Parent Theme Name: Hello Elementor
	Parent Theme Version: 2.3.0
	Parent Theme Author: Elementor Team

== User ==
	Role: administrator
	WP Profile lang: en_CA
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36

== Active Plugins ==
	Breeze
		Version: 1.1.7
		Author: Cloudways

	Business Reviews Bundle
		Version: 1.6
		Author: RichPlugins <support@richplugins.com>

	Classic Editor
		Version: 1.6
		Author: WordPress Contributors

	Elementor
		Version: 3.0.3
		Author: Elementor.com

	Elementor Pro
		Version: 3.0.1
		Author: Elementor.com

	MalCare Security - Free Malware Scanner, Protection & Security for WordPress
		Version: 4.35
		Author: MalCare Security

	Media Library Assistant
		Version: 2.84
		Author: David Lingren

	The SEO Framework
		Version: 4.1.0
		Author: The SEO Framework Team

	The SEO Framework - Extension Manager
		Version: 2.4.0
		Author: The SEO Framework Team

	WP Mail SMTP
		Version: 2.3.1
		Author: WPForms

	Yoast Duplicate Post
		Version: 3.2.5
		Author: Enrico Battocchi & Team Yoast

== Elements Usage ==
	
	header : 1
		icon : 2
		image : 1
	page : 1
		heading : 1
	section : 2
		button : 2
		icon-box : 2
		image-box : 3
		text-editor : 2
	wp-post : 0
		animated-headline : 1
		button : 8
		divider : 6
		heading : 15
		icon-list : 1
		image : 1
		image-box : 13
		image-carousel : 2
		media-carousel : 3
		menu-anchor : 7
		shortcode : 3
		text-editor : 7

== Log ==
	
JS: showing 2 of 2JS: 2020-03-04 02:44:26 [error X 1][https://wordpress-418647-1456796.cloudwaysapps.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.9.3:31:98977] Cannot read property \'message\' of null 
JS: 2020-08-29 21:48:03 [error X 15][https://wordpress-418647-1456796.cloudwaysapps.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=3.0.3:2:470394] Cannot read property \'document\' of undefined 

Log: showing 20 of 372020-06-23 13:21:24 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.12',
  'to' => '2.9.13',
)]
2020-06-29 19:26:59 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.10.2',
  'to' => '2.10.3',
)]
2020-07-21 22:58:37 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.13',
  'to' => '2.9.14',
)]
2020-08-25 20:01:41 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '2.10.3',
  'to' => '3.0.0',
)]
2020-08-25 20:01:41 [info] elementor::elementor_updater Started 
2020-08-25 20:01:41 [info] Elementor/Upgrades - _v_3_0_0_move_general_settings_to_kit Start  
2020-08-25 20:01:41 [info] Elementor/Upgrades - _v_3_0_0_move_general_settings_to_kit Finished 
2020-08-25 20:01:41 [info] Elementor/Upgrades - _v_3_0_0_move_default_colors_to_kit Start  
2020-08-25 20:01:41 [notice] System colors are disabled. nothing to do. 
2020-08-25 20:01:41 [info] Elementor/Upgrades - _v_3_0_0_move_default_colors_to_kit Finished 
2020-08-25 20:01:41 [info] Elementor/Upgrades - _v_3_0_0_move_saved_colors_to_kit Start  
2020-08-25 20:01:41 [info] Elementor/Upgrades - _v_3_0_0_move_saved_colors_to_kit Finished 
2020-08-25 20:01:41 [info] Elementor/Upgrades - _v_3_0_0_move_default_typography_to_kit Start  
2020-08-25 20:01:41 [notice] System typography is disabled. nothing to do. 
2020-08-25 20:01:41 [info] Elementor/Upgrades - _v_3_0_0_move_default_typography_to_kit Finished 
2020-08-25 20:01:41 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.14',
  'to' => '3.0.1',
)]
2020-08-25 20:01:41 [info] Elementor data updater process has been queued. [array (
  'plugin' => 'Elementor',
  'from' => '2.9.14',
  'to' => '3.0.1',
)]
2020-08-26 23:06:01 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.1',
  'to' => '3.0.2',
)]
2020-08-26 23:07:57 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor Pro',
  'from' => '3.0.0',
  'to' => '3.0.1',
)]
2020-08-27 18:08:21 [info] Elementor data updater process has been completed. [array (
  'plugin' => 'Elementor',
  'from' => '3.0.2',
  'to' => '3.0.3',
)]

PHP: showing 3 of 3PHP: 2020-04-28 18:10:30 [error X 1][/home/418647.cloudwaysapps.com/mytjedrwpm/public_html/wp-content/plugins/elementor/includes/elements/section.php::1124] Out of memory (allocated 10485760) (tried to allocate 131072 bytes) [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-08-29 18:03:53 [notice X 6][/home/418647.cloudwaysapps.com/mytjedrwpm/public_html/wp-content/plugins/elementor/core/common/modules/ajax/module.php::171] Undefined index: data [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]
PHP: 2020-08-29 18:30:26 [notice X 1][/home/418647.cloudwaysapps.com/mytjedrwpm/public_html/wp-content/plugins/elementor/includes/template-library/classes/class-import-images.php::154] Undefined index: url [array (
  'trace' => '
#0: Elementor\Core\Logger\Manager -> shutdown()
',
)]

				
</details>

### PR DESCRIPTION
**Pull request by kobizz**
## PR Checklist

- [ ] The commit message follows our guidelines:  https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

*

## Description
An explanation of what is done in this PR

*

## Test instructions
This PR can be tested by following these steps:

*

## Quality assurance

- [ ] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

Fixes #

### CODE REVIEW

File: core/upgrade/upgrades.php [hunk 1]
```diff
@@ -660,8 +661,8 @@ public static function _v_3_0_0_move_general_settings_to_kit( $updater ) {
 
 			$meta_key = \Elementor\Core\Settings\Page\Manager::META_KEY;
 			$current_settings = get_option( '_elementor_general_settings', [] );
-			$current_settings['viewport_md'] = get_option( 'elementor_viewport_md', '' );
-			$current_settings['viewport_lg'] = get_option( 'elementor_viewport_lg', '' );
+			$current_settings[ Responsive::BREAKPOINT_OPTION_PREFIX . 'md' ] = get_option( 'elementor_viewport_md', '' );
```
Comment (matipojo) [inline core/upgrade/upgrades.php:664]: On upgrade you can't use consts that may be change, it must be hard coded the exactly string that expected in the old data.

**Review by matipojo — CHANGES_REQUESTED** [review]

File: core/upgrade/upgrades.php (hunk 1 above)
Comment (kobizz) [reply core/upgrade/upgrades.php:664]: That's why I didn't touch the old data. Only the new settings that must be the same as the current breakpoints key

Comment (matipojo) [reply core/upgrade/upgrades.php:664]: `$current_settings` is refer to data from `_elementor_general_settings` that has the keys `viewport_md` and not something dynamic.

**Review by matipojo — APPROVED** [review]
