### PR TITLE
Fix: Gradient control doesn't work on frontend when using Global Colors (ED-3517)

### LINKED ISSUE #13288: Bug with global values in linear-gradient css function
This rule (applied on a color control):
```php
'selectors' => [
    '{{WRAPPER}} .elementor-button::after' => 'background-image: linear-gradient(to right {{color_from_another_control.VALUE}} 50%, {{VALUE}} 50%)',
],
```
when the color values involved are hex values (from the color-picker) correctly outputs:
```css
background-image: linear-gradient(to right, #FF0000 50%, #558ECC 50%);
```
 but breaks with custom css vars (i.e when a global color is selected) and outputs something like this:
```css
background-image: var( --e-global-color-accent_1 );
```  

Expected output would be:
```css
background-image: linear-gradient(to right, var( --e-global-color-accent_1 ) 50%, var( --e-global-color-accent_2 ) 50%);
```

### PR DESCRIPTION
**Pull request by udidol**
Fixes #13288

## PR Type
What kind of change does this PR introduce?

- [X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

* Fix: Gradient control doesn't work on frontend when using Global Colors

### CODE REVIEW

File: core/files/css/base.php [hunk 1]
```diff
@@ -700,6 +700,10 @@ private function get_style_control_value( array $control, array $values ) {
 			$value = $control['selectors_dictionary'][ $value ];
 		}
 
+		if ( ! $value && ! empty( $control['global']['default'] ) ) {
```
Comment (kobizz) [inline core/files/css/base.php:703]: Move it inside the following condition

**Review by kobizz — CHANGES_REQUESTED** [review]

File: core/files/css/base.php (hunk 1 above)
Comment (udidol) [reply core/files/css/base.php]: Done.

**Review by kobizz — APPROVED** [review]
