### PR TITLE
Tweak: Verify if SVG file exists before updating _elementor_inline_svg [#18155]

### LINKED ISSUE #18155: 🐞 Bug report: Warning: file_get_contents(/var/www/html/my-file.svg): failed to open stream: No such file or directory
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

#### What happens?
PHP tries to get an svg file content without verifying first if the file actually exists and this behaviour triggers a PHP warning.

#### What should happen?
The code should verify if the file exists before handle a resource that doesn't exist.
Error log screenshot: https://snipboard.io/39GCqc.jpg.

### Steps to reproduce

This is something not so easy to test because this issue happens when, for example, you offload your WordPress media library to a third-party service like S3.
So whenever a new image is uploaded its file is not stored in the uploads folder and Elementor fails to store the attachment metadata called `_elementor_inline_svg`.
In other words whenever you are in administration and open the media modal, Elementor fires the function `\Elementor\Core\Files\File_Types\Svg::wp_prepare_attachment_for_js` which subsequently fires `\Elementor\Core\Files\File_Types\Svg::get_inline_svg` which tries to get the metadata `_elementor_inline_svg` (but it doesn't exist) because the file was offloaded during upload.
And as the metadata doesn't exist Elementor tries to populate the field `_elementor_inline_svg` without verifying if the media exists in the uploads folder.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

== Server Environment ==
	Operating System: Linux
	Software: nginx/1.21.4
	MySQL version: Source distribution v5.7.33
	PHP Version: 7.4.26
	PHP Max Input Vars: 1000
	PHP Max Post Size: 128M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 5.9.2
	Site URL: https://www.pipefy.com
	Home URL: https://www.pipefy.com
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 1024M
	Permalink Structure: /blog/%postname%/
	Language: en-US
	Timezone: America/Sao_Paulo
	Admin Email: daniel.kossmann@pipefy.com
	Debug Mode: Inactive

== Theme ==
	Name: Pipefy 2020
	Version: 1.0.0
	Author: Pipefy
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields: Icon Font
		Version: 1.0.0
		Author: Kreshnik Hasanaj

	Advanced Custom Fields PRO
		Version: 5.12
		Author: Delicious Brains

	Advanced Database Cleaner PRO
		Version: 3.1.7
		Author: Younes JFR.

	Elementor
		Version: 3.5.6
		Author: Elementor.com

	Elementor Pro
		Version: 3.6.3
		Author: Elementor.com

	EWWW Image Optimizer
		Version: 6.4.1
		Author: Exactly WWW

	RDDS Blocks
		Version: 1.0.0
		Author: Redstamp

	Redirection
		Version: 5.2.3
		Author: John Godley

	Relevanssi
		Version: 4.14.7
		Author: Mikko Saari

	Sucuri Security - Auditing, Malware Scanner and Hardening
		Version: 1.8.30
		Author: Sucuri Inc.

	W3 Total Cache
		Version: 2.2.1
		Author: BoldGrid

	WordPress Sentry
		Version: 4.13.1
		Author: Alex Bouma

	WP 2FA - Two-factor authentication for WordPress
		Version: 2.1.0
		Author: WP White Security

	WP Activity Log (Premium)
		Version: 4.4.0
		Author: WP White Security

	WP Activity Log for Yoast SEO
		Version: 1.2.0
		Author: WP White Security

	WPassword
		Version: 2.5.1
		Author: WP White Security

	WP Mail SMTP
		Version: 3.3.0
		Author: WPForms

	WPML Multilingual CMS
		Version: 4.4.11
		Author: OnTheGoSystems

	WPML String Translation
		Version: 3.1.9
		Author: OnTheGoSystems

	WP Offload Media Lite
		Version: 2.5.5
		Author: Delicious Brains

	Yoast Duplicate Post
		Version: 4.4
		Author: Enrico Battocchi & Team Yoast

	Yoast SEO
		Version: 18.2
		Author: Team Yoast

	Yoast SEO: Video
		Version: 14.3
		Author: Team Yoast

	Yoast SEO Premium
		Version: 18.1
		Author: Team Yoast

== Elementor Experiments ==
	Optimized DOM Output: Inactive
	Improved Asset Loading: Active
	Improved CSS Loading: Active
	Inline Font Icons: Inactive by default
	Accessibility Improvements: Inactive by default
	Import Export Template Kit: Active by default
	Additional Custom Breakpoints: Inactive by default
	Hide native WordPress widgets from search results: Active by default
	Default to New Theme Builder: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default
	Page Transitions: Active by default
	Form Submissions: Active by default
	Scroll Snap: Active by default

== Log ==
	

== Elementor - Compatibility Tag ==
	
	Elementor Pro: Compatibility not specified

== Elementor Pro - Compatibility Tag ==

### PR DESCRIPTION
**Pull request by filipecsweb**
## PR Checklist

- [x] The commit message follows our guidelines:  https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

* Verify if svg file exists before updating `_elementor_inline_svg` and avoid PHP warning (Fixes #18155).

## Description
An explanation of what is done in this PR

* Verify if svg file exists before updating _elementor_inline_svg and avoid warning: `failed to open stream: No such file or directory`.

## Test instructions
This PR can be tested by following these steps:

* Please, check the issue https://github.com/elementor/elementor/issues/18155.

## Quality assurance

- [x] I have tested this code to the best of my abilities
- [x] I have added unittests to verify the code works as intended
- [x] Docs have been added / updated (for bug fixes / features)

Fixes #

### CODE REVIEW

File: core/files/file-types/svg.php [hunk 1]
```diff
@@ -290,7 +290,7 @@ public static function get_inline_svg( $attachment_id ) {
 
 		$attachment_file = get_attached_file( $attachment_id );
 
-		if ( ! $attachment_file ) {
+		if ( ! $attachment_file || ! file_exists( $attachment_file ) ) {
```
Comment (udidol) [inline core/files/file-types/svg.php:293]: Why not just
```suggestion
		if ( ! file_exists( $attachment_file ) ) {
```
?

Comment (filipecsweb) [reply core/files/file-types/svg.php]: @udidol it makes sense! I just changed the code.

**Comment by udidol** [comment]
@filipecsweb In order to commit code into Elementor, you need to have a github account and sign our CLA agreement. You have all the details in your main PR screen (the "Conversation" tab)

**Comment by filipecsweb** [comment]
> @filipecsweb In order to commit code into Elementor, you need to sign our CLA agreement. You have all the details in your main PR screen (the "Conversation" tab)

Hi @udidol. Done!

**Comment by udidol** [comment]
@filipecsweb For our integration tests to pass, please change the PR title to:
`Tweak: Verify if SVG file exists before updating _elementor_inline_svg [#18155]`

**Comment by filipecsweb** [comment]
@udidol I received an email with your request about changing the title but it seems you already made the change.
Anyway, Is everything good on my side?

**Comment by udidol** [comment]
@filipecsweb Yes I ended up changing it myself. No need for anything else on your side, your PR is probably going to be merged soon.

**Review by udidol — APPROVED** [review]
