### PR TITLE
Fix: Error message appears on front if WooCommerce is activated (#19533) [ED-8032]

### LINKED ISSUE #19533: 🐞 Bug report: Unable to save the page if copy and paste the styles of a widget
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

The issue occurs with the Display Conditions feature of our plugin PowerPack for Elementor. If I copy and paste the styles from one widget to the other and then try to save the page, a JS error is shown in the console, and the page doesn't save. The error started showing after Elementor 3.7.0. If I turn off the display conditions, the page will save without any issue.

The issue is not only seen in PowerPack, but I have also tried a few other plugins, and the same issue is seen with Display Conditions.

Adding repeater controls on widgets, sections or containers seems to have a bug with the latest Elementor.

Screenshot 2022-08-19 at 7 58 46 AM

### Steps to reproduce

1. Add any widget twice to the page like the Heading widget.
2. Copy the first heading widget and paste style on the second heading widget.
3. Now, when you try to save the page, it will not save but shows a JS error in the console.

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ ] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

					
== Server Environment ==
	Operating System: Darwin
	Software: Apache/2.4.46 (Unix) OpenSSL/1.0.2u PHP/8.0.8 mod_wsgi/3.5 Python/2.7.18 mod_fastcgi/mod_fastcgi-SNAP-0910052141 mod_perl/2.0.11 Perl/v5.30.1
	MySQL version: MySQL Community Server (GPL) v5.7.34
	PHP Version: 8.0.8
	PHP Memory Limit: 128M
	PHP Max Input Vars: 1000
	PHP Max Post Size: 8M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 6.0.1
	Site URL: http://localhost:8888/wplab
	Home URL: http://localhost:8888/wplab
	WP Multisite: No
	Max Upload Size: 8 MB
	Memory limit: 512M
	Max Memory limit: 256M
	Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
	Language: en-US
	Timezone: 5.5
	Admin Email: simrankalsi2004@yahoo.co.in
	Debug Mode: Active

== Theme ==
	Name: Hello Elementor
	Version: 2.5.0
	Author: Elementor Team
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36

== Active Plugins ==
	Elementor
		Version: 3.7.1
		Author: Elementor.com

	PowerPack Pro for Elementor
		Version: 2.9.7
		Author: Team IdeaBox - PowerPack Elements

== Elements Usage ==
	
	page : 1
		button : 1
		heading : 8
		image : 3
		pp-divider : 2
		pp-info-list : 6
		pp-video : 1
		text-editor : 1
	section : 6
		button : 136
		heading : 11
		image : 1
		pp-advanced-accordion : 21
		pp-advanced-menu : 1
		pp-breadcrumbs : 1
		pp-coupons : 1
		pp-faq : 1
		pp-image-gallery : 1
		pp-info-box : 5
		pp-posts : 2
		pp-video : 1
		spacer : 1
		text-editor : 10
		video : 1
	wp-page : 4
		accordion : 1
		button : 1
		heading : 2
		icon : 2
		icon-box : 1
		icon-list : 1
		image : 1
		image-carousel : 1
		pp-categories : 2
		pp-counter : 1
		pp-info-box : 2
		pp-logo-carousel : 1
		pp-modal-popup : 2
		pp-offcanvas-content : 2
		pp-posts : 1
		star-rating : 1
		tabs : 1
		text-editor : 3

== Elementor Experiments ==
	Optimized DOM Output: Active by default
	Improved Asset Loading: Active by default
	Improved CSS Loading: Active by default
	Inline Font Icons: Inactive
	Accessibility Improvements: Active by default
	Additional Custom Breakpoints: Active
	Import Export Template Kit: Active by default
	Hide native WordPress widgets from search results: Active by default
	admin_menu_rearrangement: Inactive by default
	Flexbox Container: Inactive by default
	Hello Theme Header & Footer: Active by default
	Landing Pages: Active by default
	Color Sampler: Active by default
	Favorite Widgets: Active by default
	Admin Top Bar: Active by default

== Log ==
	

== Elementor - Compatibility Tag ==
	
	PowerPack Pro for Elementor: Compatible

### PR DESCRIPTION
**Pull request by StyleShit**
Closes #19533

### CODE REVIEW

File: core/base/document.php [hunk 1]
```diff
@@ -264,7 +264,7 @@ public function get_main_id() {
 	/**
 	 * @return null|Lock_Behavior
 	 */
-	public function get_lock_behavior() {
+	public static function get_lock_behavior() {
```
Comment (matipojo) [inline core/base/document.php:267]:
```suggestion
	public static function get_lock_behavior_v2() {
```

**Review by matipojo — CHANGES_REQUESTED** [review]
Please avoid core/pro dependency
