### PR TITLE
Fix: Vertical alignment issue in Safari user agents closes #9034

### LINKED ISSUE #9034: vertical align bug
after update to 2.7.0 the vertical align is not working with safari both iphones and mac OS (it's align automatically to the top or not work at all, didn't have time to debug it, just make a rollback to v-2.6.8)
if you want i can make a duplicate website with the problem that you can debug it.

### PR DESCRIPTION
**Pull request by shilo-ey**
## PR Checklist

- [ ] The commit message follows our guidelines:  https://github.com/elementor/elementor/blob/master/.github/CONTRIBUTING.md

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

*

## Description
An explanation of what is done in this PR

*

## Test instructions
This PR can be tested by following these steps:

*

## Quality assurance

- [ ] I have tested this code to the best of my abilities
- [ ] I have added unittests to verify the code works as intended
- [ ] Docs have been added / updated (for bug fixes / features)

Fixes #

### CODE REVIEW

File: includes/elements/column.php [hunk 1]
```diff
@@ -174,7 +174,7 @@ protected function _register_controls() {
 					// TODO: The following line is for BC since 2.7.0
 					'.elementor-bc-flex-widget {{WRAPPER}}.elementor-column .elementor-column-wrap' => 'align-items: {{VALUE}}',
 					// This specificity is intended to make sure column css overwrites section css on vertical alignment (content_position)
-					'{{WRAPPER}}.elementor-column.elementor-element[data-element_type="column"] > .elementor-column-wrap.elementor-element-populated > .elementor-widget-wrap' => 'align-content: {{VALUE}}',
+					'{{WRAPPER}}.elementor-column.elementor-element[data-element_type="column"] > .elementor-column-wrap.elementor-element-populated > .elementor-widget-wrap' => 'align-content: {{VALUE}};  align-items: {{VALUE}};',
```
Comment (KingYes) [inline includes/elements/column.php]:
```suggestion
					'{{WRAPPER}}.elementor-column.elementor-element[data-element_type="column"] > .elementor-column-wrap.elementor-element-populated > .elementor-widget-wrap' => 'align-content: {{VALUE}}; align-items: {{VALUE}};',
```

**Review by KingYes — CHANGES_REQUESTED** [review]
