### PR TITLE
Fix: Background Image - Custom X  Position doesn't work for non-desktop devices [ED-8224]

### LINKED ISSUE #19487: 🐞 Bug report: The custom size option in background overlay is not displayed on mobiles and tablets.
### Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

### Description

Please watch the following video :

https://user-images.githubusercontent.com/77163248/184641137-eb4d512a-b25f-4b7b-a26a-112fc838261a.mp4

As you can see in the video above, the width option is not displayed on tablets and mobile phones.

### Steps to reproduce

video

### Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a Blank WordPress theme active ([Hello theme](https://wordpress.org/themes/hello-elementor/)).
- [X] I can reproduce this bug consistently using the steps above.

### System Info

-

### PR DESCRIPTION
**Pull request by udidol**
## PR Type
What kind of change does this PR introduce?

- [X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Summary

This PR can be summarized in the following changelog entry:

* Fix: Background Image - Custom X  Position doesn't work for non-desktop devices
* Fix: Using responsive controls within control `selectors` value placeholders `{{control_name}}` always takes the desktop value

## Description
An explanation of what is done in this PR

* Closes #19487

### CODE REVIEW

**Review by TzviRabinovitch — APPROVED** [review]

File: includes/managers/controls.php [hunk 1]
```diff
@@ -1078,6 +1078,24 @@ public function get_teaser_template( $texts ) {
 		return ob_get_clean();
 	}
 
+	/**
+	 * Get Responsive Control Device Suffix
+	 *
+	 * @param array $control
+	 * @return string $device suffix
+	 */
+	public static function get_responsive_control_device_suffix( array $control ): string {
```
Comment (StuartElementor) [inline includes/managers/controls.php:1087]: `:string` - are we specifying return types now?

Comment (udidol) [reply includes/managers/controls.php:1087]: We have officially dropped support for PHP 5.6. Since we now support PHP >7 we can do this. I believe our PHPCS even hints for it
