### PR TITLE
Tweak: Added Elementor price plan filter to Kit Library (closes #16075) [ED-4804]

### LINKED ISSUE #16075: Elementor Template Kit Library: "Expert" tag doesn't show nothing. I expected it to show Expert Templates.
## Prerequisites

- [ x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x ] The issue still exists against the latest stable version of Elementor.

## Description
I'm in the new Elementor Template Kit Library trying to filter kits from Free, Pro and Expert Plans. The problem is that the "Tags" only feature the "Expert" and it shows nothing.

## Steps to reproduce
Go to the new Template Kit Library and use the tag "Expert". Nothing will show up.
image

## Isolating the problem

- [ x ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ x ] This bug happens with a default WordPress theme active.
- [ x ] I can reproduce this bug consistently using the steps above.

## Environment
Fresh elementor install
<details>
<summary>System Info</summary>
```
<!-- For bug reports, let us know about your system environment: Copy and paste the system info report from Elementor => System info, and paste it here or in http://pastebin.com/ -->
```
</details>

### PR DESCRIPTION
**Pull request by Nevoss**

### CODE REVIEW

File: core/app/modules/kit-library/data/base-controller.php [hunk 1]
```diff
@@ -20,9 +22,18 @@ abstract class Base_Controller extends Controller {
 	 */
 	public function get_repository() {
 		if ( ! $this->repository ) {
+			/** @var Module $connect */
```
Comment (StyleShit) [inline core/app/modules/kit-library/data/base-controller.php:25]: Maybe use the whole namespace since `Module` is generic?

```suggestion
			/** @var Elementor\Core\Common\Modules\Connect\Module $connect */
```

File: core/app/modules/kit-library/data/base-controller.php [hunk 2]
```diff
@@ -20,9 +22,18 @@ abstract class Base_Controller extends Controller {
...
+				->map( function ( $value ) {
+					return $value['label'];
+				} );
+
 			$this->repository = new Repository(
-				Plugin::$instance->common->get_component( 'connect' )->get_app( 'kit-library' ),
-				new User_Favorites( get_current_user_id() )
+				$connect->get_app( 'kit-library' ),
+				new User_Favorites( get_current_user_id() ),
+				$subscription_plans
```
Comment (StyleShit) [inline core/app/modules/kit-library/data/base-controller.php:36]: DI Container could've been nice here 😅

File: core/app/modules/kit-library/data/repository.php [hunk 3]
```diff
@@ -213,11 +226,15 @@ private function get_taxonomies_data( $force_api_request = false ) {
...
-		}, [] );
+		$subscription_plan_tag = $this->subscription_plans->get( $kit->access_level );
+
+		$taxonomies = ( new Collection( static::TAXONOMIES_KEYS ) )
+			->reduce( function ( Collection $current, $key ) use ( $kit ) {
+				return $current->merge(
+					( new Collection( $kit->{$key} ) )->pluck( 'name' )
+				);
+			}, new Collection( [] ) )
+			->merge( [ $subscription_plan_tag ? $subscription_plan_tag : 'Free' ] );
```
Comment (StyleShit) [inline core/app/modules/kit-library/data/repository.php:237]: Explain, and maybe make it more readable, it's really messy and complicated in my opinion.

**Review by StyleShit — CHANGES_REQUESTED** [review]

File: core/app/modules/kit-library/data/base-controller.php (hunk 1 above)
Comment (Nevoss) [reply core/app/modules/kit-library/data/base-controller.php:25]: DONE

File: core/app/modules/kit-library/data/repository.php (hunk 3 above)
Comment (Nevoss) [reply core/app/modules/kit-library/data/repository.php]: Done

File: core/app/modules/kit-library/data/repository.php [hunk 4]
```diff
@@ -228,13 +228,11 @@ private function get_taxonomies_data( $force_api_request = false ) {
...
-				return $current->merge(
-					( new Collection( $kit->{$key} ) )->pluck( 'name' )
-				);
-			}, new Collection( [] ) )
-			->merge( [ $subscription_plan_tag ? $subscription_plan_tag : 'Free' ] );
+		$taxonomies = ( new Collection( (array) $kit ) )
+			->only( static::TAXONOMIES_KEYS )
+			->flatten()
+			->pluck( 'name' )
+			->push( $subscription_plan_tag ? $subscription_plan_tag : 'Free' );
```
Comment (StyleShit) [inline core/app/modules/kit-library/data/repository.php:235]: 🚀

**Review by StyleShit — APPROVED** [review]

File: core/app/modules/kit-library/data/repository.php [hunk 5]
```diff
@@ -97,6 +102,14 @@ public function get_taxonomies( $force_api_request = false ) {
 					];
 				}, $taxonomies ) );
 			}, new Collection( [] ) )
+			->merge(
+				$this->subscription_plans->map( function ( $label ) {
+					return [
+						'text' => $label ? $label : 'Free',
```
Comment (matipojo) [inline core/app/modules/kit-library/data/repository.php:108]: Explain + why not translate

File: core/common/modules/connect/module.php [hunk 6]
```diff
@@ -184,7 +184,7 @@ public function get_categories() {
 	 *
 	 * @return array
 	 */
-	public function get_subscription_plans( $context ) {
+	public function get_subscription_plans( $context = '' ) {
```
Comment (matipojo) [inline core/common/modules/connect/module.php:187]: PHPDoc

File: tests/phpunit/elementor/core/app/kit-library/data/taxonomies/test-controller.php [hunk 7]
```diff
@@ -82,6 +82,20 @@ public function test_get_items() {
 				'text' => 'Creative',
 				'type' => 'tags',
 			],
+
+			// Subscription plans added as taxonomies locally and not from server
+			[
+				'text' => 'Free',
+				'type' => 'subscription_plans'
```
Comment (matipojo) [inline tests/phpunit/elementor/core/app/kit-library/data/taxonomies/test-controller.php:89]: Use constants

**Review by matipojo — CHANGES_REQUESTED** [review]

File: core/common/modules/connect/module.php (hunk 6 above)
Comment (Nevoss) [reply core/common/modules/connect/module.php:187]: Done

File: tests/phpunit/elementor/core/app/kit-library/data/taxonomies/test-controller.php (hunk 7 above)
Comment (Nevoss) [reply tests/phpunit/elementor/core/app/kit-library/data/taxonomies/test-controller.php]: Done

**Review by matipojo — APPROVED** [review]
